# Generated by Django 5.1.6 on 2025-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='selectedTest',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
