# Generated by Django 5.1.6 on 2025-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patientregister_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='injectionDetails',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='patientregister',
            name='injectionRequired',
            field=models.BooleanField(default=False),
        ),
    ]
