# Generated by Django 5.1.6 on 2025-04-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patientregister_injectiondetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='selectedTest',
            field=models.CharField(blank=True, default='No', max_length=225, null=True),
        ),
    ]
